### ISSUE TITLE
Warning about the texture 'createutilities:block/void_slots'

### ISSUE THREAD

**Issue by Xyphenore** [Duqueeee/create-utilities#6]
**Describe the bug**

The texture 'createutilities:block/void_slots' prints a warning on the console.

'Texture createutilities:block/void_slots with size 8x8 limits mip level from 4 to 3'

**To Reproduce**

- Install the mod.
- Run the game with the output console.
- Warning is printed on console

**Additional context**
- Mod version: 0.1.3 for 1.20.1
- Forge version: 47.1.47
- Create version: 0.5.1b for 1.20.1

**Comment by Duqueeee** [comment]
Hi! Thank you for bringing this to my attention! The issue has been fixed in the lastest patch of the mod.
You can download it in the following links:
**Curseforge: https://www.curseforge.com/minecraft/mc-mods/createutilities/files/4758006**
**Modrinth: https://modrinth.com/mod/create-utilities/version/hf8LzCk9**
